<a href="https://colab.research.google.com/github/NITIN9694/TensorFlow-Learning/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

##Data Type & Attributes

In [20]:
a2 = [[1.,2.,3.3],
      [4.,5.,6.5]
      ]


In [21]:
a2

[[1.0, 2.0, 3.3], [4.0, 5.0, 6.5]]

In [22]:
import pandas as pd

In [23]:
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## Creating  Array

In [24]:
sample_array = np.array([1,2,3])

In [25]:
sample_array

array([1, 2, 3])

In [26]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2,3))

In [28]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [30]:
range_array = np.arange(0,10,2)

In [31]:
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0,10,size = (3,5))

In [33]:
random_array

array([[9, 8, 5, 6, 1],
       [1, 2, 3, 1, 6],
       [2, 0, 4, 2, 1]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [38]:
random_array_2= np.random.random((5,3))

In [39]:
random_array_2.shape

(5, 3)

In [43]:
 #random_seed
random_array3 = np.random.rand(5,3)

In [44]:
random_array3

array([[0.66884579, 0.84123267, 0.7650324 ],
       [0.36459915, 0.83290353, 0.83148474],
       [0.85774246, 0.2586457 , 0.52468067],
       [0.15895685, 0.71631299, 0.25174106],
       [0.47209376, 0.75553148, 0.09186625]])

In [67]:
np.random.seed(seed=10)
random_array4 = np.random.randint(10,size =( 5,3))
random_array4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

##Viewing array and metrics

In [68]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[4, 6, 8, 1, 8],
         [4, 1, 3, 6, 5],
         [3, 9, 6, 9, 1],
         [9, 4, 2, 6, 7]],

        [[8, 8, 9, 2, 0],
         [6, 7, 8, 1, 7],
         [1, 4, 0, 8, 5],
         [4, 7, 8, 8, 2]],

        [[6, 2, 8, 8, 6],
         [6, 5, 6, 0, 0],
         [6, 9, 1, 8, 9],
         [1, 2, 8, 9, 9]]],


       [[[5, 0, 2, 7, 3],
         [0, 4, 2, 0, 3],
         [3, 1, 2, 5, 9],
         [0, 1, 0, 1, 9]],

        [[0, 9, 2, 1, 1],
         [0, 0, 5, 9, 0],
         [4, 6, 6, 0, 2],
         [3, 3, 2, 6, 0]],

        [[5, 1, 3, 6, 5],
         [5, 1, 8, 0, 5],
         [9, 8, 5, 7, 8],
         [5, 8, 9, 9, 1]]]])

In [70]:
a4.shape

(2, 3, 4, 5)

In [71]:
a4.ndim

4

In [74]:
#Get first 4 number
a4[:,:,:,:1]

array([[[[4],
         [4],
         [3],
         [9]],

        [[8],
         [6],
         [1],
         [4]],

        [[6],
         [6],
         [6],
         [1]]],


       [[[5],
         [0],
         [3],
         [0]],

        [[0],
         [0],
         [4],
         [3]],

        [[5],
         [5],
         [9],
         [5]]]])

## Manipulating & Comparing arrays

In [76]:
a1 = np.array([1,2,3])

In [77]:
a1

array([1, 2, 3])

In [78]:
one = np.ones(3)
one

array([1., 1., 1.])

In [79]:
a1 + one

array([2., 3., 4.])

In [80]:
a2

[[1.0, 2.0, 3.3], [4.0, 5.0, 6.5]]

In [81]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

##Aggregation
Aggregation = performing the same operation on a number of things




In [85]:
listy_list = [1,2,3]
type(listy_list)

list

In [86]:
a1

array([1, 2, 3])

In [88]:
type(a1)

numpy.ndarray

In [89]:
sum(a1)

np.int64(6)

In [90]:
np.sum(a1)

np.int64(6)

In [91]:
#creative a massive numpy array
massive_array = np.random.random(100000)
massive_array[:10]

array([0.51233415, 0.67346693, 0.15919373, 0.05047767, 0.33781589,
       0.10806377, 0.17890281, 0.8858271 , 0.36536497, 0.21876935])

In [92]:
%timeit sum(massive_array) #pyhton sum
%timeit np.sum(massive_array) #numpy sum

12.2 ms ± 3.47 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.3 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Use Python's methods (sum()) on Python datatypes and use Numpy's methods on Numpy arrays (np.sum())

In [93]:
a2


[[1.0, 2.0, 3.3], [4.0, 5.0, 6.5]]

In [94]:
np.mean(a2)

np.float64(3.6333333333333333)

In [95]:
np.max(a2)

np.float64(6.5)

In [97]:
np.std(a2)

np.float64(1.8226964152656422)

In [98]:
#variance = measure if the average degree to which each number is diffrent to the mean
# Higer Varince = wider range of numbers
# Lower varince = lower range of numbers
np.var(a2)

np.float64(3.3222222222222224)